#-----------------------------------
--- # Application
#-----------------------------------

server:
  port: 9091

spring:
  profiles:
    active: default

#-----------------------------------
--- # Database H2
#-----------------------------------

spring:
  config:
    activate:
      on-profile: default

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
  messages:
    encoding: UTF-8
    basename: i18n/messages
  output:
    ansi:
      enabled: always

logging:
  level:
    com:
      tujuhsembilan: TRACE

#-----------------------------------
--- # Authentication
#-----------------------------------

application:
  security:
    uuid: b592691e-df3f-4049-86d5-50bdce269354
    strength: 8
    system-username: SYSTEM
    system-password: $2a$16$Pjg5ZRu.I2TsN5W38PMyQuYBorSrwmRKa/4fc01nEZl0FSOQeou3C # SYSADM


#-----------------------------------
--- # Database PostgreSQL
#-----------------------------------

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://localhost:5432/notes-app
    driver-class-name: org.postgresql.Driver
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  messages:
    encoding: UTF-8
    basename: i18n/messages
  output:
    ansi:
      enabled: always

#-----------------------------------
--- # Logging
#-----------------------------------

logging:
  level:
    com:
      tujuhsembilan: TRACE


#-----------------------------------
--- # Miscellanous
#-----------------------------------

spring:
  output:
    ansi:
      enabled: always # Just console color, I'm lovin' it!

# # -----------------------------------
# --- #
# # -----------------------------------
